import os
from openai import OpenAI

class LLMAdapter:
    def __init__(self, client=None, model: str = "gpt-5-mini"):
        """
        client: LLM client or wrapper
        """
        self.client = client or OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
        self.model = model

    def generate_sql(self, user_query: str, schema: dict) -> str:
        """
        Convert a natural language query into SQL.
        Returns the SQL string generated by the LLM.
        """
        prompt = self.build_prompt(user_query, schema)

        response = self.client.responses.create(
            model=self.model,
            input=prompt
        )

        return response.output_text.strip()

    def build_prompt(self, user_query: str, schema: dict) -> str:
        """
        Create the prompt sent to the LLM.
        """
        schema_lines = []

        for table_name, table_info in schema.items():
            columns = ", ".join(table_info["columns"].keys())
            schema_lines.append(f"- {table_name} ({columns})")

        schema_text = "\n".join(schema_lines)

        prompt = f"""
You are an assistant that converts natural language questions into safe SQLite SELECT queries.

Rules:
- Only generate a single SQLite SELECT query
- Do not generate INSERT, UPDATE, DELETE, DROP, ALTER, or CREATE
- Use only tables and columns from the schema
- Do not include markdown fences
- Do not include explanation text
- Return only the SQL query

Database schema:
{schema_text}

User request:
{user_query}
""".strip()

        return prompt