class LLMAdapter:
    def __init__(self, client):
        """
        client: LLM client or wrapper
        """
        pass

    def generate_sql(self, user_query: str, schema: dict) -> str:
        """
        Convert a natural language query into SQL.
        Returns the SQL string generated by the LLM.
        """
        pass

    def build_prompt(self, user_query: str, schema: dict) -> str:
        """
        Create the prompt sent to the LLM.
        """
        pass